import test from 'node:test';import assert from 'node:assert/strict';import {callTool} from '../lib/tools.mjs';
test('Recovered registry accounts for 64×8 original sheet rows without replacing BL',async()=>{const c=await callTool('get_research_registry',{});assert.equal(c.mbss.branches.length,64);assert.equal(c.mbss.classifiers,512);assert.equal(c.extension.templates,96);const seen=new Set();for(let offset=0;offset<512;offset+=12){const r=await callTool('get_research_registry',{collection:'mbss',offset,limit:12});r.definitions.forEach(x=>{assert.ok(!seen.has(x.id));seen.add(x.id);assert.ok(x.source_ref.row>=2)});assert.equal(r.total,512)}assert.equal(seen.size,512);assert.equal((await callTool('get_business_logic_registry',{})).classifier_count,384)});
test('Reserved branch numbers do not silently collide',async()=>{const a=await callTool('get_research_registry',{collection:'mbss',branch:'B49'}),b=await callTool('get_research_registry',{collection:'extension',ids:['EXT:MB49.01']});assert.match(a.definitions[0].branch,/Authentication/);assert.match(b.definitions[0].group,/Concurrency/);assert.equal(b.definitions[0].status,'CANDIDATE_NOT_ADOPTED')});
test('Every extension definition remains accessible in its separate namespace',async()=>{const seen=new Set();for(let offset=0;offset<96;offset+=12){const r=await callTool('get_research_registry',{collection:'extension',offset});r.definitions.forEach(x=>seen.add(x.id))}assert.equal(seen.size,96);assert.ok(seen.has('EXT:DP-H.04'))});
test('Cross references resolve exact parent definitions and bound neighbors',async()=>{const r=await callTool('cross_reference_methods',{ids:['MBSS-B02-L01','BL01.01','EXT:DP-A.01'],limit:4});assert.equal(r.selected.length,3);assert.equal(r.related.length,4);assert.equal(r.next_offset,4);assert.ok(r.canonical_parents.some(x=>x.id===31));assert.equal(r.semantic_equivalence_established,false);for(const x of r.related)assert.ok(x.shared_parent_ids.length>0)});
test('Invalid, duplicate and mixed selectors fail explicitly',async()=>{for(const a of [{collection:'mbss',ids:['bogus']},{collection:'mbss',ids:['MBSS-B01-L01'],branch:'B01'},{collection:'mbss',branch:'B65'},{collection:'extension',offset:100},{collection:'catalog',ids:['x']}])await assert.rejects(()=>callTool('get_research_registry',a));await assert.rejects(()=>callTool('cross_reference_methods',{ids:['BL01.01','BL01.01']}))});
test('Jacket comparison preserves all independent axes and rejects implicit multi-axis changes',async()=>{const {definition:j}=await callTool('get_research_registry',{collection:'jacket'});assert.equal(j.axes.length,14);const left=j.axes.map(axis=>({axis,states:['UNKNOWN'],source_refs:[]})),right=structuredClone(left);right.find(x=>x.axis==='LITERAL').states=['OBSERVED'];right.find(x=>x.axis==='LITERAL').source_refs=['synthetic-page-1'];const r=await callTool('compare_operative_states',{term:'acknowledge',left,right});assert.equal(r.changed_axis,'LITERAL');assert.equal(r.preserved_axes.length,13);assert.equal(r.legal_effect_changed,'NOT_DETERMINED');assert.equal(r.canonical_promotion,false);right.find(x=>x.axis==='ELECTION_WAIVER').states=['MARKED_ELECTED'];right.find(x=>x.axis==='ELECTION_WAIVER').source_refs=['synthetic-page-1'];await assert.rejects(()=>callTool('compare_operative_states',{term:'acknowledge',left,right}),/ONE_COORDINATE/) });
test('Jacket no-op, missing axes and unsupported states are rejected',async()=>{const {definition:j}=await callTool('get_research_registry',{collection:'jacket'});const rows=j.axes.map(axis=>({axis,states:['UNKNOWN'],source_refs:[]}));await assert.rejects(()=>callTool('compare_operative_states',{term:'word',left:rows,right:rows}),/NO_OP/);const bad=structuredClone(rows);bad[0].states=['AUTHENTICATED'];await assert.rejects(()=>callTool('compare_operative_states',{term:'word',left:rows,right:bad}),/SOURCE_REFERENCE/)});
test('Ordinary answer contract is reachable from existing connector tools',async()=>{const c=await callTool('get_universal_contract',{});assert.equal(c.normal_answer_contract.version,'RECON-OUTPUT-1.0');assert.ok(c.normal_answer_contract.rules.some(x=>x.includes('binary')));assert.equal(c.normal_answer_contract.model_output_guaranteed,false)});
