import registry from './research-registry.json' with {type:'json'};
import bl from './solid-state-pack.json' with {type:'json'};
import bundle from './registry-bundle.json' with {type:'json'};
import {digest} from './universal.mjs';
const s={type:'string',minLength:1,maxLength:300};
const arr=(items,min=0,max=24)=>({type:'array',items,minItems:min,maxItems:max});
const obj=(properties,required=Object.keys(properties))=>({type:'object',properties,required,additionalProperties:false});
const enums=xs=>({type:'string',enum:xs});
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v)}return v};freeze(registry);
export const outputContract=freeze({version:'RECON-OUTPUT-1.0',purpose:'Readable review of supplied evidence, backed by exact registry links',sections:['Observed record and exact source','Classifier and parent references','What the record supports','What remains inferred or unknown','Contrary explanation / falsifier','Missing evidence and stop condition'],rules:['Do not dump the registry into normal answers. Show only referenced IDs and material distinctions.','Preserve printed identity, operative function, actor/capacity, authority, time/version and finality separately.','A shared MAXVAR parent is a cross-reference, not equivalence or proof.','Method agreement is not independent corroboration.','Report the evidence state on each axis; a binary pass/fail is not a substitute.','No automated target actions or vulnerability reproduction are executed by these lookup tools.'],default_call_budget:3,preferred_parallel_calls:1,model_output_guaranteed:false});
export const researchSchema=obj({collection:enums(['catalog','mbss','extension','jacket','framework']),branch:s,ids:arr(s,1,12),offset:{type:'integer',minimum:0,maximum:608},limit:{type:'integer',minimum:1,maximum:12}},[]);
export const crossSchema=obj({ids:arr(s,1,8),offset:{type:'integer',minimum:0,maximum:512},limit:{type:'integer',minimum:1,maximum:24}},['ids']);
const axisSchema=obj({axis:enums(registry.jacket.axes),states:arr(enums(registry.jacket.states),1,8),source_refs:arr(s,0,8)});
export const operativeSchema=obj({term:s,left:arr(axisSchema,14,14),right:arr(axisSchema,14,14)});
const fail=m=>{throw Error(m)};
const parents=raw=>{const ids=new Set();for(const part of raw.split(',')){const m=part.trim().match(/^(\d+)(?:-(\d+))?$/);if(!m)fail('PARENT_MAPPING_PARSE_ERROR');const lo=+m[1],hi=+(m[2]??m[1]);if(lo<1||hi>256||hi<lo)fail('PARENT_RANGE_ERROR');for(let i=lo;i<=hi;i++)ids.add(i)}return [...ids].sort((a,b)=>a-b)};
const mbss=registry.mbss.classifiers.map(c=>({id:c['Classifier ID'],branch_id:c['Branch ID'],branch:c.Branch,lens:c.Lens,method_lineage:c['Method Lineage'],question:c['Question / Predicate'],invariant:c['Core Branch Invariant'],expected_state:c['Expected Safe State'],falsifier:c['Falsifier / Benign Explanation'],evidence_target:c['Passive Evidence Target'],parent_maxvar_ids:parents(c['MAXVAR Parent Hooks']),status:c.Status,source_ref:{document_id:registry.mbss.source_id,tab:'Classifiers',row:c.source_row},implementation:'RECOVERED_REVIEW_DEFINITION_NOT_EXECUTED'}));
const extensions=registry.extension.definitions.map(c=>({...c,id:'EXT:'+c.id,parent_maxvar_ids:parents(c.parent_mapping_literal),source_ref:{document_id:registry.extension.source_id,revision:registry.extension.revision_id,start_index:c.source_start_index},implementation:'CANDIDATE_REVIEW_DEFINITION_NOT_EXECUTED'}));
const records=new Map([...mbss,...extensions,...bl.classifiers.map(c=>({id:c.id,branch_id:c.branch_id,method_lineage:c.method_sources,parent_maxvar_ids:c.parent_maxvar_ids,question:c.predicate_template,implementation:'LEGACY_BL_REVIEW_DEFINITION'}))].map(c=>[c.id,c]));
let checked;
async function ready(){return checked??=(async()=>{if(mbss.length!==512||registry.mbss.branches.length!==64||extensions.length!==96||records.size!==992)fail('RESEARCH_REGISTRY_COUNT_MISMATCH');for(const b of registry.mbss.branches)if(mbss.filter(c=>c.branch_id===b['Branch ID']).length!==8)fail('RESEARCH_BRANCH_COUNT_MISMATCH');for(const [name,b] of Object.entries(bundle))if(await digest(b.raw)!==b.sha256)fail('PARENT_REGISTRY_DIGEST_MISMATCH:'+name);return digest(registry)})()}
export async function getResearchRegistry({collection='catalog',branch,ids,offset=0,limit=12}={}){
 const fingerprint=await ready();if(ids&&(branch||offset))fail('USE_IDS_OR_PAGINATION');if(ids&&new Set(ids).size!==ids.length)fail('DUPLICATE_ID');
 const base={registry_version:registry.version,registry_fingerprint:fingerprint,canonical_promotion:false,external_action_authorized:false};
 if(collection==='catalog'){if(branch||ids||offset)fail('SELECT_COLLECTION_FIRST');return {...base,mbss:{version:registry.mbss.version,branches:registry.mbss.branches.map(b=>({id:b['Branch ID'],label:b.Branch,children:8})),classifiers:512,source_id:registry.mbss.source_id},extension:{templates:96,status:registry.extension.status,collision_note:registry.extension.collision_note},jacket:{axes:registry.jacket.axes.length,source_id:registry.jacket.source_id},framework:registry.framework,output_contract:outputContract,lookup_instruction:'Choose mbss or extension; use exact IDs (max 12) or offset/limit. EXT: prefixes distinguish draft template IDs.'}}
 if(collection==='jacket'||collection==='framework'){if(branch||ids||offset)fail('SELECTOR_NOT_APPLICABLE');return {...base,definition:registry[collection],output_contract:outputContract}}
 let rows=collection==='mbss'?mbss:extensions;if(ids){const byId=new Map(rows.map(c=>[c.id,c]));if(ids.some(id=>!byId.has(id)))fail('UNKNOWN_CLASSIFIER_ID');rows=ids.map(id=>byId.get(id))}else if(branch){rows=rows.filter(c=>c.branch_id===branch||c.group===branch);if(!rows.length)fail('UNKNOWN_BRANCH')}
 const total=rows.length;if(offset>total)fail('OFFSET_OUT_OF_RANGE');const page=rows.slice(offset,offset+limit);return {...base,collection,total,definitions:page,next_offset:offset+page.length<total?offset+page.length:null,definitions_are_findings:false};
}
export async function crossReferenceMethods({ids,offset=0,limit=12}){
 const fingerprint=await ready();if(new Set(ids).size!==ids.length)fail('DUPLICATE_ID');if(ids.some(id=>!records.has(id)))fail('UNKNOWN_CLASSIFIER_ID');const selected=ids.map(id=>records.get(id)),p=new Set(selected.flatMap(c=>c.parent_maxvar_ids));
 const max=JSON.parse(bundle['maxvar256.json'].raw);const related=mbss.filter(c=>!ids.includes(c.id)&&c.parent_maxvar_ids.some(id=>p.has(id)));if(offset>related.length)fail('OFFSET_OUT_OF_RANGE');const page=related.slice(offset,offset+limit);
 return {registry_fingerprint:fingerprint,selected,canonical_parents:max.dimensions.filter(d=>p.has(d.id)),related:page.map(c=>({id:c.id,branch_id:c.branch_id,shared_parent_ids:c.parent_maxvar_ids.filter(id=>p.has(id)),relation:'SHARED_DECLARED_PARENT_ONLY',source_ref:c.source_ref})),related_total:related.length,next_offset:offset+page.length<related.length?offset+page.length:null,reverse_lookup:'Query any returned ID to obtain its own parent definitions and sibling references.',semantic_equivalence_established:false,nestmax_domain_mapping:'Use get_nestmax_registry for the separate program/IID pack; not automatically applied across domains.',output_contract:outputContract,canonical_promotion:false,external_action_authorized:false};
}
export async function compareOperativeStates({term,left,right}){
 for(const rows of [left,right]){if(new Set(rows.map(x=>x.axis)).size!==14)fail('EVERY_AXIS_EXACTLY_ONCE');for(const r of rows){if(new Set(r.states).size!==r.states.length)fail('DUPLICATE_AXIS_STATE');if(r.states.some(s=>s!=='UNKNOWN')&&!r.source_refs.length)fail('SOURCE_REFERENCE_REQUIRED')}}
 const map=new Map(right.map(x=>[x.axis,x]));const changed=left.filter(x=>JSON.stringify([...x.states].sort())!==JSON.stringify([...map.get(x.axis).states].sort())||JSON.stringify([...x.source_refs].sort())!==JSON.stringify([...map.get(x.axis).source_refs].sort())).map(x=>x.axis);
 if(changed.length!==1)fail(changed.length?'ONE_COORDINATE_REQUIRED':'NO_OP_COMPARISON');
 return {status:'OPERATIVE_AXIS_COMPARISON',term,changed_axis:changed[0],preserved_axes:registry.jacket.axes.filter(x=>x!==changed[0]),before:left.find(x=>x.axis===changed[0]),after:map.get(changed[0]),comparison_fingerprint:await digest({term,left,right}),rule:registry.jacket.rule,axis_states:'CALLER_DECLARED_NOT_AUTHENTICATED',legal_effect_changed:'NOT_DETERMINED',needs_separate_atom:'REVIEW_REQUIRED',source_ref:{document_id:registry.jacket.source_id,revision:registry.jacket.revision_id},canonical_promotion:false,court_release_allowed:false,external_action_authorized:false};
}
