import {validate} from './schema.mjs';
// Portable structural contract. No provider SDK, network, database, or legal inference.
const s={type:'string',minLength:1,maxLength:10000},h={type:'string',minLength:64,maxLength:64};
const obj=p=>({type:'object',properties:p,required:Object.keys(p),additionalProperties:false});
const arr=(items,min=0,max=64)=>({type:'array',items,minItems:min,maxItems:max});
const strings=arr(s,1);
export const sourceSchema=obj({namespace:s,source_id:s,version:s,owner:s,subject_ids:strings,native_locator:s,representation:s,text:{...s,maxLength:200000},text_sha256:h});
const spanSchema=obj({span_id:s,source_id:s,source_version:s,source_fingerprint:h,subject_id:s,start:{type:'integer',minimum:0,maximum:200000},end:{type:'integer',minimum:1,maximum:200000},exact_text:{...s,maxLength:200000}});
const claimSchema=obj({claim_id:s,subject_id:s,actor:s,capacity:s,statement:s,state:{type:'string',enum:['OBSERVED','DERIVED','INFERRED','ADOPTED']},span_ids:strings,parent_claim_ids:arr(s),method:s,limitations:strings});
export const packetSchema=obj({contract_version:{type:'string',enum:['1.0.0']},namespace:s,domain_profile:s,packet_id:s,sources:arr(sourceSchema,1,8),spans:arr(spanSchema,1),claims:arr(claimSchema,1)});
export const universalInputSchema=obj({packet:packetSchema,expected_packet_fingerprint:{type:['string','null'],minLength:64,maxLength:64}});
export const universalContract={contract_version:'1.0.0',purpose:'Domain-neutral evidence-reference structural validation',packet_schema:packetSchema,offset_unit:'UNICODE_CODE_POINT',hash_encoding:'SHA256_UTF8',serialization:'Sorted object keys using JavaScript UTF-16 order; JSON.stringify primitive encoding; array order preserved; schema admits only integer numbers. Versioned custom format, not a JCS conformance claim.',states:['OBSERVED','DERIVED','INFERRED','ADOPTED'],adoption:'Blocked: requires a separate trusted proof and approval gate.',adapters:'Adapters supply declared sources; this module does not retrieve or authenticate them.',compatibility:'Separate universal contract; does not replace the Python proof-gate packet or registry.',authorization:'Pure read-only function; no dispatch, persistence, external action, or automatic promotion.'};
export function canonical(v){if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(v!==null&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';return JSON.stringify(v)}
export async function digest(v){const b=new TextEncoder().encode(typeof v==='string'?v:canonical(v));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function validateUniversal({packet,expected_packet_fingerprint}){
 validate({packet,expected_packet_fingerprint},universalInputSchema);
 const findings=[],sourceMap=new Map(),spanMap=new Map(),claimMap=new Map(),sourceFingerprints=[],sourceDigests=new Map(),sourceChars=new Map();
 const add=(code,id)=>findings.push({code,id});
 const key=(id,version)=>JSON.stringify([id,version]);
 // Do not normalize source text or identifiers; the exact provided representation is bound.
 for(const source of packet.sources){const id=key(source.source_id,source.version);if(sourceMap.has(id))add('DUPLICATE_SOURCE_VERSION',source.source_id);sourceMap.set(id,source);if(source.namespace!==packet.namespace)add('CROSS_NAMESPACE_SOURCE',source.source_id);if(!/^[0-9a-f]{64}$/.test(source.text_sha256)||await digest(source.text)!==source.text_sha256)add('TEXT_HASH_MISMATCH',source.source_id);if(new Set(source.subject_ids).size!==source.subject_ids.length)add('DUPLICATE_SUBJECT',source.source_id);sourceDigests.set(id,await digest(source));sourceChars.set(id,[...source.text]);sourceFingerprints.push({source_id:source.source_id,version:source.version,fingerprint:sourceDigests.get(id)})}
 for(const span of packet.spans){if(spanMap.has(span.span_id))add('DUPLICATE_SPAN_ID',span.span_id);spanMap.set(span.span_id,span);const source=sourceMap.get(key(span.source_id,span.source_version));if(!source){add('UNRESOLVED_SOURCE_VERSION',span.span_id);continue}if(sourceDigests.get(key(span.source_id,span.source_version))!==span.source_fingerprint)add('SOURCE_ENVELOPE_CHANGED',span.span_id);if(!source.subject_ids.includes(span.subject_id))add('SUBJECT_NOT_DECLARED_BY_SOURCE',span.span_id);const chars=sourceChars.get(key(span.source_id,span.source_version));if(span.end<=span.start||span.end>chars.length||chars.slice(span.start,span.end).join('')!==span.exact_text)add('EXACT_SPAN_MISMATCH',span.span_id)}
 for(const claim of packet.claims){if(claimMap.has(claim.claim_id))add('DUPLICATE_CLAIM_ID',claim.claim_id);claimMap.set(claim.claim_id,claim);if(claim.state==='ADOPTED')add('ADOPTION_GATE_NOT_IMPLEMENTED',claim.claim_id);for(const id of claim.span_ids){const span=spanMap.get(id);if(!span)add('UNRESOLVED_SPAN',claim.claim_id);else if(span.subject_id!==claim.subject_id)add('CLAIM_SUBJECT_MISMATCH',claim.claim_id)}if(['DERIVED','INFERRED'].includes(claim.state)&&!claim.parent_claim_ids.length)add('MISSING_PARENT_CLAIM',claim.claim_id)}
 const visiting=new Set(),done=new Set();function visit(id){if(visiting.has(id)){add('CLAIM_DEPENDENCY_CYCLE',id);return}if(done.has(id))return;const claim=claimMap.get(id);if(!claim){add('UNRESOLVED_PARENT_CLAIM',id);return}visiting.add(id);claim.parent_claim_ids.forEach(visit);visiting.delete(id);done.add(id)}packet.claims.forEach(c=>visit(c.claim_id));
 const fingerprint=await digest(packet);if(expected_packet_fingerprint!==null&&fingerprint!==expected_packet_fingerprint)add('PACKET_CHANGED','packet');
 return {status:findings.length?'BLOCKED':'STRUCTURAL_REFERENCE_CHECK_PASS',contract_version:'1.0.0',packet_fingerprint:fingerprint,source_fingerprints:sourceFingerprints,findings,declared_domain_profile:packet.domain_profile,domain_profile_executed:false,native_authentication:false,subject_attribution_verified:false,claim_truth_verified:false,expected_fingerprint_authenticated:false,persisted:false,canonical_promotion:false,court_release_allowed:false,next_check:findings.length?'Resolve reported reference failures.':'Review actual subject attribution, claim support, applicability, and approval against trusted original evidence.'};
}
